spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:censorgram}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    table: tp_schema_information
  data:
    web:
      pageable:
        one-indexed-parameters: true

logging.level.org.flywaydb: debug
logging.level.org.springframework.security: trace


moderator:
  base-url: ${MODERATOR_BASE_URL:http://localhost:5000/moderator}
  api.inspect: /inspect
  confidence-limit: 0.95
